security:
    encoders:
        FOS\UserBundle\Model\UserInterface:              sha1

    role_hierarchy:
        ROLE_ADMIN:        ROLE_USER
        ROLE_CATEGORY:     ROLE_ADMIN
        ROLE_POST:         ROLE_ADMIN
        ROLE_SUPER_ADMIN:  [ROLE_CATEGORY, ROLE_SUPERA_DMIN]
    providers:
        admin:
            id:            fos_user.user_provider.username
    firewalls:
        dev:
            pattern:       ^/(_(profiler|wdt)|css|images|js)/
            security:      false
        admin:
            form_login:
                provider:        admin
                csrf_provider:  form.csrf_provider
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
            logout:
                path:            fos_user_security_logout
                target:          @BackendHome
            anonymous:           true
    access_control:
        - { path: ^/admin/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/category,       roles: ROLE_CATEGORY }
        - { path: ^/admin/post,       roles: ROLE_POST }
        - { path: ^/admin/user,       roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/,       roles: ROLE_ADMIN }
